language: php

php:
    - "7.1"

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./vendor/bin/php-cs-fixer --dry-run -v fix
    - ./vendor/bin/phpspec run
